services:

  # InterSystems IRIS 
  iris:
    build:
      context: iris
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 1972:1972
      - 52773:52773
    volumes:
      - ./:/app
      - ./iris/durabledata:/durabledata
    environment:
    - ISC_DATA_DIRECTORY=/durabledata