services:

  # InterSystems IRIS 
  iris-fhir-agent:
    build:
      context: iris
      dockerfile: Dockerfile
    container_name: iris-fhir-agent
    ports:
      - 1973:1972
      - 52774:52773
    volumes:
      - ./:/app
      - ./iris/durabledata:/durabledata
    environment:
    - ISC_DATA_DIRECTORY=/durabledata